
select * from data.customer_data;

-- Q1. What is the total revenue generated by male vs. female customers?
DESCRIBE data.customer_data;

SELECT gender, SUM(`Purchase Amount (USD)`) AS revenue 
FROM data.customer_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

  
SELECT `Customer ID`, `Purchase Amount (USD)`
FROM data.customer_data 
  where `Purchase Amount (USD)` >= (       
      SELECT AVG(`Purchase Amount (USD)`)        
      FROM data.customer_data        
      where `Discount Applied` LIKE '%Yes%'   
  );

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT `Item Purchased`, ROUND(AVG(`Review Rating`),2) AS `Average Product Rating`
FROM data.customer_data
GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC
LIMIT 5;


-- Q4. Compare the average Purchase amounts between Standard and Express Shipping.

SELECT `Shipping Type`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS `Average Purchase`
FROM data.customer_data
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and  non-subscribers.

SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM data.customer_data
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT `Item Purchased`,
       ROUND(SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
FROM data.customer_data
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on 
-- their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT `Customer ID`, `Previous Purchases`, 
           CASE 
               WHEN `Previous Purchases` = 1 THEN 'New'
               WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment 
    FROM data.customer_data
)
SELECT customer_segment, COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;


-- Q8. .What are the top 3 most purchased products within each category?



WITH item_counts AS (
    SELECT category,
           `Item Purchased`,
           COUNT(`Customer ID`) AS total_orders,
           ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(`Customer ID`) DESC) AS item_rank
    FROM data.customer_data
    GROUP BY category, `Item Purchased`
)
SELECT category, `Item Purchased`, total_orders, item_rank
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select `Subscription Status`, 
count(`Customer Id`) as report_buyers
FROM data.customer_data
where `Previous Purchases` > 5
group by `Subscription Status` ;

-- Q10. What is the revenue contribution of each age group?

SELECT 
    CASE 
        WHEN `Age` BETWEEN 18 AND 31 THEN 'Young Adult'
        WHEN `Age` BETWEEN 32 AND 44 THEN 'Adult'
        WHEN `Age` BETWEEN 45 AND 57 THEN 'Middle-aged'
        ELSE 'Senior'
    END AS `Age Group`,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM data.customer_data
GROUP BY `Age Group`
ORDER BY total_revenue DESC;
